export const menuTypes = {
  NEW_PRODUCT: "NEW_PRODUCT",
  UPDATE_PRODUCT: "UPDATE_PRODUCT",
  DELETE_PRODUCT: "DELETE_PRODUCT",
  LIST_PRODUCTS: "LIST_PRODUCTS",
  NEW_USER: "NEW_USER",
  UPDATE_USER: "UPDATE_USER",
  DELETE_USER: "DELETE_USER",
  LIST_USERS: "LIST_USERS",
  SALES: "SALES",
};
